using System.Numerics;
using JulschaVehicleTool.Core.Models;

namespace JulschaVehicleTool.Core.Constants;

public static class HandlingPresets
{
    public static readonly (string Name, Func<HandlingData> Create)[] All =
    [
        ("Sports Car", CreateSportsCar),
        ("Muscle Car", CreateMuscleCar),
        ("SUV / Truck", CreateSuv),
        ("Motorcycle", CreateMotorcycle),
        ("Boat", CreateBoat),
        ("Helicopter", CreateHelicopter),
    ];

    public static HandlingData CreateSportsCar() => new()
    {
        HandlingName = "SPORTSCAR",
        FMass = 1500f,
        FInitialDragCoeff = 6.5f,
        FPercentSubmerged = 85f,
        VecCentreOfMassOffset = new Vector3(0f, 0f, -0.12f),
        VecInertiaMultiplier = new Vector3(1.2f, 1.1f, 1.4f),
        FDriveBiasFront = 0f,
        NInitialDriveGears = 6,
        FInitialDriveForce = 0.36f,
        FDriveInertia = 1.0f,
        FClutchChangeRateScaleUpShift = 2.6f,
        FClutchChangeRateScaleDownShift = 2.4f,
        FInitialDriveMaxFlatVel = 180f,
        FBrakeForce = 1.2f,
        FBrakeBiasFront = 0.65f,
        FHandBrakeForce = 0.8f,
        FSteeringLock = 38f,
        FTractionCurveMax = 2.55f,
        FTractionCurveMin = 2.25f,
        FTractionCurveLateral = 22.5f,
        FTractionSpringDeltaMax = 0.15f,
        FLowSpeedTractionLossMult = 1.0f,
        FTractionBiasFront = 0.485f,
        FTractionLossMult = 1.0f,
        FSuspensionForce = 2.4f,
        FSuspensionCompDamp = 1.4f,
        FSuspensionReboundDamp = 2.2f,
        FSuspensionUpperLimit = 0.1f,
        FSuspensionLowerLimit = -0.1f,
        FSuspensionBiasFront = 0.5f,
        FAntiRollBarForce = 0.85f,
        FAntiRollBarBiasFront = 0.6f,
        FRollCentreHeightFront = 0.32f,
        FRollCentreHeightRear = 0.32f,
        FCollisionDamageMult = 1.0f,
        FWeaponDamageMult = 1.0f,
        FDeformationDamageMult = 0.8f,
        FEngineDamageMult = 1.5f,
        FPetrolTankVolume = 60f,
        FOilVolume = 5f,
        NMonetaryValue = 150000,
        StrModelFlags = "440010",
        StrHandlingFlags = "0",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };

    public static HandlingData CreateMuscleCar() => new()
    {
        HandlingName = "MUSCLECAR",
        FMass = 1800f,
        FInitialDragCoeff = 7.0f,
        FPercentSubmerged = 85f,
        VecCentreOfMassOffset = new Vector3(0f, 0.05f, -0.15f),
        VecInertiaMultiplier = new Vector3(1.3f, 1.2f, 1.5f),
        FDriveBiasFront = 0f,
        NInitialDriveGears = 5,
        FInitialDriveForce = 0.34f,
        FDriveInertia = 1.0f,
        FClutchChangeRateScaleUpShift = 2.0f,
        FClutchChangeRateScaleDownShift = 2.0f,
        FInitialDriveMaxFlatVel = 160f,
        FBrakeForce = 0.8f,
        FBrakeBiasFront = 0.55f,
        FHandBrakeForce = 0.6f,
        FSteeringLock = 40f,
        FTractionCurveMax = 2.1f,
        FTractionCurveMin = 1.85f,
        FTractionCurveLateral = 22.5f,
        FTractionSpringDeltaMax = 0.14f,
        FTractionBiasFront = 0.48f,
        FTractionLossMult = 1.2f,
        FSuspensionForce = 2.0f,
        FSuspensionCompDamp = 1.3f,
        FSuspensionReboundDamp = 2.0f,
        FSuspensionUpperLimit = 0.12f,
        FSuspensionLowerLimit = -0.12f,
        FSuspensionBiasFront = 0.48f,
        FAntiRollBarForce = 0.7f,
        FAntiRollBarBiasFront = 0.55f,
        FRollCentreHeightFront = 0.36f,
        FRollCentreHeightRear = 0.36f,
        FCollisionDamageMult = 1.0f,
        FWeaponDamageMult = 1.0f,
        FDeformationDamageMult = 0.8f,
        FEngineDamageMult = 1.5f,
        FPetrolTankVolume = 75f,
        FOilVolume = 5f,
        NMonetaryValue = 65000,
        StrModelFlags = "440010",
        StrHandlingFlags = "0",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };

    public static HandlingData CreateSuv() => new()
    {
        HandlingName = "SUV",
        FMass = 2500f,
        FInitialDragCoeff = 8.5f,
        FPercentSubmerged = 80f,
        VecCentreOfMassOffset = new Vector3(0f, 0f, -0.2f),
        VecInertiaMultiplier = new Vector3(1.3f, 1.3f, 1.4f),
        FDriveBiasFront = 0.5f,
        NInitialDriveGears = 6,
        FInitialDriveForce = 0.28f,
        FDriveInertia = 1.0f,
        FClutchChangeRateScaleUpShift = 2.4f,
        FClutchChangeRateScaleDownShift = 2.2f,
        FInitialDriveMaxFlatVel = 140f,
        FBrakeForce = 0.8f,
        FBrakeBiasFront = 0.6f,
        FHandBrakeForce = 0.55f,
        FSteeringLock = 40f,
        FTractionCurveMax = 2.0f,
        FTractionCurveMin = 1.8f,
        FTractionCurveLateral = 22.5f,
        FTractionSpringDeltaMax = 0.15f,
        FTractionBiasFront = 0.5f,
        FTractionLossMult = 1.0f,
        FSuspensionForce = 2.2f,
        FSuspensionCompDamp = 1.6f,
        FSuspensionReboundDamp = 2.4f,
        FSuspensionUpperLimit = 0.15f,
        FSuspensionLowerLimit = -0.12f,
        FSuspensionBiasFront = 0.5f,
        FAntiRollBarForce = 0.7f,
        FAntiRollBarBiasFront = 0.5f,
        FRollCentreHeightFront = 0.45f,
        FRollCentreHeightRear = 0.45f,
        FCollisionDamageMult = 0.8f,
        FWeaponDamageMult = 1.0f,
        FDeformationDamageMult = 0.6f,
        FEngineDamageMult = 1.5f,
        FPetrolTankVolume = 80f,
        FOilVolume = 6f,
        NMonetaryValue = 55000,
        StrModelFlags = "440010",
        StrHandlingFlags = "20",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };

    public static HandlingData CreateMotorcycle() => new()
    {
        HandlingName = "MOTORCYCLE",
        FMass = 200f,
        FInitialDragCoeff = 5.0f,
        FPercentSubmerged = 70f,
        VecCentreOfMassOffset = new Vector3(0f, 0f, -0.05f),
        VecInertiaMultiplier = new Vector3(1.0f, 1.0f, 1.3f),
        FDriveBiasFront = 0f,
        NInitialDriveGears = 6,
        FInitialDriveForce = 0.35f,
        FDriveInertia = 0.95f,
        FClutchChangeRateScaleUpShift = 3.0f,
        FClutchChangeRateScaleDownShift = 3.0f,
        FInitialDriveMaxFlatVel = 170f,
        FBrakeForce = 0.7f,
        FBrakeBiasFront = 0.6f,
        FHandBrakeForce = 0.35f,
        FSteeringLock = 38f,
        FTractionCurveMax = 2.15f,
        FTractionCurveMin = 1.95f,
        FTractionCurveLateral = 22.5f,
        FTractionSpringDeltaMax = 0.12f,
        FTractionBiasFront = 0.485f,
        FTractionLossMult = 1.0f,
        FSuspensionForce = 2.5f,
        FSuspensionCompDamp = 1.2f,
        FSuspensionReboundDamp = 2.0f,
        FSuspensionUpperLimit = 0.12f,
        FSuspensionLowerLimit = -0.08f,
        FSuspensionBiasFront = 0.5f,
        FAntiRollBarForce = 0f,
        FAntiRollBarBiasFront = 0.5f,
        FCollisionDamageMult = 3.0f,
        FWeaponDamageMult = 3.0f,
        FDeformationDamageMult = 1.0f,
        FEngineDamageMult = 3.0f,
        FPetrolTankVolume = 20f,
        FOilVolume = 3f,
        NMonetaryValue = 25000,
        StrModelFlags = "440010",
        StrHandlingFlags = "0",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };

    public static HandlingData CreateBoat() => new()
    {
        HandlingName = "BOAT",
        FMass = 3000f,
        FInitialDragCoeff = 5.0f,
        FPercentSubmerged = 75f,
        VecCentreOfMassOffset = new Vector3(0f, 0f, -0.5f),
        VecInertiaMultiplier = new Vector3(1.0f, 1.0f, 1.0f),
        FDriveBiasFront = 0.5f,
        NInitialDriveGears = 1,
        FInitialDriveForce = 0.2f,
        FDriveInertia = 1.0f,
        FClutchChangeRateScaleUpShift = 1.6f,
        FClutchChangeRateScaleDownShift = 1.6f,
        FInitialDriveMaxFlatVel = 90f,
        FBrakeForce = 0.3f,
        FBrakeBiasFront = 0.5f,
        FHandBrakeForce = 0f,
        FSteeringLock = 40f,
        FTractionCurveMax = 1.0f,
        FTractionCurveMin = 0.5f,
        FTractionBiasFront = 0.5f,
        FTractionLossMult = 1.0f,
        NMonetaryValue = 80000,
        StrModelFlags = "0",
        StrHandlingFlags = "0",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };

    public static HandlingData CreateHelicopter() => new()
    {
        HandlingName = "HELI",
        FMass = 6000f,
        FInitialDragCoeff = 2.5f,
        FPercentSubmerged = 85f,
        VecCentreOfMassOffset = new Vector3(0f, 0f, 0.2f),
        VecInertiaMultiplier = new Vector3(1.5f, 1.0f, 1.5f),
        FDriveBiasFront = 0.5f,
        NInitialDriveGears = 1,
        FInitialDriveForce = 0.25f,
        FDriveInertia = 1.0f,
        FClutchChangeRateScaleUpShift = 1.6f,
        FClutchChangeRateScaleDownShift = 1.6f,
        FInitialDriveMaxFlatVel = 180f,
        FBrakeForce = 1.0f,
        FBrakeBiasFront = 0.5f,
        FHandBrakeForce = 0f,
        FSteeringLock = 40f,
        FTractionCurveMax = 1.0f,
        FTractionCurveMin = 0.5f,
        FTractionBiasFront = 0.5f,
        FTractionLossMult = 1.0f,
        FCollisionDamageMult = 2.0f,
        FWeaponDamageMult = 2.0f,
        FEngineDamageMult = 2.0f,
        FPetrolTankVolume = 500f,
        NMonetaryValue = 500000,
        StrModelFlags = "0",
        StrHandlingFlags = "0",
        StrDamageFlags = "0",
        AiHandling = "AVERAGE",
    };
}
